import logging
import os
import random

import numpy as np
import torch
import torch.optim as optim
from omegaconf import DictConfig
from torch.utils.data import DataLoader

from src.dataset import CustomPTDataset
from src.loss import TruncatedLoss
from src.model import get_model
from src.task import train_epoch


class TrainPipeline:
    """
    Training pipeline:
    1. Load pre-split train.pt and val.pt (generated by src/preprocess.py).
    2. Train on train.pt with Truncated Loss, monitoring val accuracy each epoch.
    3. Save the trained model as base_model.pt in results_dir.

    Instantiated by Hydra via conf/config.yaml.
    Run `python -m src.preprocess` first to generate train.pt and val.pt.
    """

    def __init__(
        self,
        data: DictConfig,
        training: DictConfig,
        loss: DictConfig,
    ) -> None:
        self.data = data
        self.training = training
        self.loss = loss

        torch.manual_seed(training.seed)
        np.random.seed(training.seed)
        random.seed(training.seed)

        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        logging.info("Using device: %s", self.device)

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def run(self, results_dir: str = ".") -> None:
        train_loader, train_dataset = self._build_dataloaders()
        model = self._train(train_loader, train_dataset)

        model_path = os.path.join(results_dir, "base_model.pt")
        torch.save(model.state_dict(), model_path)
        logging.info("Base model saved to: %s", model_path)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _build_dataloaders(
        self,
    ) -> tuple[DataLoader, DataLoader, CustomPTDataset]:
        train_dataset = CustomPTDataset(
            self.data.train_path,
            return_index=True,
            split="train",
            is_labelled=True,
            augmentation_factor=self.training.augmentation_factor,
        )

        train_loader = DataLoader(train_dataset, batch_size=self.training.batch_size, shuffle=True)

        return train_loader, train_dataset

    def _train(
        self,
        train_loader: DataLoader,
        train_dataset: CustomPTDataset,
    ) -> torch.nn.Module:
        model = get_model(num_classes=self.training.num_classes).to(self.device)
        criterion = TruncatedLoss(
            q=self.loss.q,
            k=self.loss.k,
            trainset_size=len(train_dataset),
        ).to(self.device)
        optimizer = optim.Adam(model.parameters(), lr=self.training.lr)

        for epoch in range(self.training.epochs):
            loss = train_epoch(model, train_loader, criterion, optimizer, self.device)

            logging.info(
                "Epoch %d/%d | Loss: %.4f",
                epoch + 1,
                self.training.epochs,
                loss,
            )

        return model
